name: Scheduled healthcheck


on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 20 * * 0'

jobs:
  scheduled_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the app url
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://fs-pokedex-app.herokuapp.com/